#define ARCH_X86_64

#include "exception.hh"
#include "numeric.hh"
#include "inotify.hh"
#include "fast_deque.hh"
#include "cache.hh"
#include "rwlock-posix.hh"
#include "probe.hh"
#include "sockaddress.hh"
//#include "rt-message.hh"
#include "singleton.hh"
#include "atomic.hh"
#include "pthread++.hh"
#include "iptables.hh"
#include "itoa.hh"
#include "sprint.hh"
#include "matrix.hh"
#include "socket.hh"
#include "arch-cpu.hh"
#include "function-factory.hh"
//#include "singleton.hh"
#include "strtox.hh"
#include "syslog.hh"
#include "functor.hh"
#include "factory.hh"
#include "refcnt.hh"
#include "tuple.hh"
#include "memory-policy.hh"
#include "getopt.hh"
#include "singleton_proc.hh"
#include "cpuinfo.hh"
#include "atomicity-policy.hh"
#include "typelist.hh"
// #include "xmlParser.hh"

#include "dump_container.hh"
#include "mtp.hh"
#include "type_traits.hh"

int main()
{}
